### PR TITLE
Post feature

### PR DESCRIPTION
**Pull request by AnjarTiyo**
complete all related posts-feature and fix several code on users-001

### CODE REVIEW

**Comment by AnjarTiyo** [comment]
there are also several project structure update and that was important for generating report. So i highly recommend to update toward this latest structure @bungaayu @brahmasyahdan

**Review by bungaayu — APPROVED** [review]
LGTM

**Comment by brahmasyahdan** [comment]
LGTM

**Review by brahmasyahdan — APPROVED** [review]
LGTM

**Pull request merged**
